'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Upstairs

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMasterBedroomLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterBedroomLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnMasterBedroomLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBedroomLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterBedroomLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBedroomLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMasterBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterBedroomFan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnMasterBedroomFanOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBedroomFanOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterBedroomFanOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBedroomFanOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMasterBathroomLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterBathroomLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnMasterBathroomLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBathroomLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterBathroomLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBathroomLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMasterClosetLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterClosetLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnMasterClosetLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterClosetLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterClosetLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterClosetLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblKidsHallwayLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKidsHallwayLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnKidsHallwayLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKidsHallwayLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKidsHallwayLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKidsHallwayLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSpareBedroomLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpareBedroomLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSpareBedroomLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareBedroomLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSpareBedroomLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareBedroomLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSpareBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpareBedroomFan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSpareBedroomFanOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareBedroomFanOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSpareBedroomFanOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareBedroomFanOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSydneyBedroomLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSydneyBedroomLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSydneyBedroomLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSydneyBedroomLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSydneyBedroomLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSydneyBedroomLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSydneyBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSydneyBedroomFan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSydneyBedroomFanOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSydneyBedroomFanOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSydneyBedroomFanOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSydneyBedroomFanOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEthanBedroomLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEthanBedroomLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEthanBedroomLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEthanBedroomLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEthanBedroomLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEthanBedroomLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEthanBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEthanBedroomFan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEthanBedroomFanOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEthanBedroomFanOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEthanBedroomFanOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEthanBedroomFanOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblKidsBathroomLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKidsBathroomLight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnKidsBathroomLightOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKidsBathroomLightOn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKidsBathroomLightOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKidsBathroomLightOff As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
