'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm2

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnMasterBedroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBedroom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEthanBedroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEthanBedroom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBedroomFan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEthanBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEthanBedroomFan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterBathroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterBathroom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSydneyBedroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSydneyBedroom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMasterCloset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasterCloset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSydneyBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSydneyBedroomFan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKidsHallway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKidsHallway As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSpareBedroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareBedroom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKidsBathroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKidsBathroom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSpareBedroomFan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareBedroomFan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMudRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMudRoom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSpiderLamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpiderLamp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPantry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPantry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSconceLights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSconceLights As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFDCoach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFDCoach As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnGDCoach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGDCoach As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKitchen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKitchen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPlayRoomEast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPlayRoomEast As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKitchenNook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKitchenNook As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPlayRoomWest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPlayRoomWest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLivingRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLivingRoom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShellLamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShellLamp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBackyardSpot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackyardSpot As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDiningRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiningRoom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFrontHall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFrontHall As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBasementStairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBasementStairs As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBasementN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBasementN As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnArtRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnArtRoom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBasementMid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBasementMid As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnServerRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServerRoom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBasementS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBasementS As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTestLamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTestLamp As Global.System.Web.UI.WebControls.Button
End Class
